### ISSUE TITLE
If you have only one pet allow !feed etc to work without giving pet index/name

### ISSUE THREAD

**Issue by egelmex** [fleure/kentpet#1]

**Comment by ElvenSpellmaker** [comment]
@fleure Doesn't this now work?

I mean, you have to set it manually, but it does work once the default pet is set.

**Comment by fleure** [comment]
In terms of usability it is a little redundant, though. If the number of your pets is just 1, it makes sense that you shouldn't _need_ to set your defaultpet or keep specifying "1" for various commands.

**Comment by fleure** [comment]
Commands that referred to a user's default pet will now assume the first pet if no pet specified and no default pet set.
