### ISSUE TITLE
!petinfo not displaying correct information

### ISSUE THREAD

**Issue by fleure** [fleure/kentpet#14]
17:01 < graymalkin> !petinfo 1
17:01 < kentpet> graymalkin: Pet info // James XVII // Level 7 // HP: 100 // Food: Hungry
17:01 < graymalkin> !petinfo 2
17:01 < kentpet> graymalkin: Pet info // (o-o) // James XVIII // Level 1 // HP: 100 // Food: Hungry
17:07 < catboy> !petinfo 1 --owner graymalkin
17:07 < kentpet> catboy: Pet info // James XVII // Level 7 // HP: 100 // Food: Bloated
17:06 < catboy> !petinfo 2 --owner graymalkin
17:06 < kentpet> catboy: Pet info // (o-o) // James XVIII // Level 1 // HP: 100 // Food: Full

Likely to do with extracting pet information in get_pet().

**Comment by fleure** [comment]
@graymalkin is a bad tester and my logging needs to be better. Non-issue.

**Comment by graymalkin** [comment]
!
